# Generated by Django 4.2.7 on 2025-11-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum order value for this rate",
                        max_digits=10,
                    ),
                ),
                (
                    "max_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum order value (leave empty for unlimited)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order value above which shipping is free",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India",
                        help_text="Applicable country (India, USA, etc.)",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Lower number = higher priority"
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "min_order_value"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("razorpay", "Razorpay (UPI)"), ("paypal", "PayPal")],
                max_length=20,
            ),
        ),
    ]
