# Generated by Django 4.2.7 on 2025-11-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_shippingrate_alter_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("north", "North India"),
                            ("south", "South India"),
                            ("east", "East India"),
                            ("west", "West India"),
                            ("central", "Central India"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="States/regions covered in this zone"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base shipping cost for this zone",
                        max_digits=10,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Order value above which shipping is free",
                        max_digits=10,
                    ),
                ),
                (
                    "delivery_days",
                    models.CharField(
                        blank=True, help_text="Estimated delivery time", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["zone"],
            },
        ),
        migrations.CreateModel(
            name="PincodeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pincode",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pincodes",
                        to="shop.shippingzone",
                    ),
                ),
            ],
            options={
                "ordering": ["pincode"],
                "indexes": [
                    models.Index(
                        fields=["pincode"], name="shop_pincod_pincode_b41318_idx"
                    )
                ],
            },
        ),
    ]
