# Generated by Django 4.2.7 on 2025-11-08 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_shippingzone_pincodezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingzone",
            name="cost",
        ),
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=0.1,
                help_text="Product weight in kilograms (e.g., 0.500 for 500g)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.001)],
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="cost_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Shipping cost per kilogram for this zone",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="free_shipping_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                help_text="Order value above which shipping is free",
                max_digits=10,
            ),
        ),
    ]
