# Generated by Django 4.2.7 on 2025-11-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_shippingzone_cost_product_weight_kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pincodezone",
            name="country",
            field=models.CharField(
                default="India", help_text="Country for this pincode", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="pincodezone",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pincodes",
                to="shop.shippingzone",
            ),
        ),
        migrations.AddIndex(
            model_name="pincodezone",
            index=models.Index(
                fields=["country"], name="shop_pincod_country_2d883a_idx"
            ),
        ),
    ]
