# Generated by Django 4.2.7 on 2025-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_add_country_to_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingrate",
            name="min_shipping_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Minimum shipping charge for this country (₹)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, help_text="Cost per kilogram (₹/kg)", max_digits=10
            ),
        ),
    ]
